kind: pipeline
name: build_linux_amd64

clone:
  depth: 50

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: binary
    image: golang:1.12
    pull: true
    commands:
      - export LD_FLAGS="-w -s -X main.Version=$(git describe --tags | cut -c 2-) -X main.BuildDate=$(date "+%F-%T") -X main.Commit=$(git rev-parse --verify HEAD) -X main.Mode=prod"
      - make build_linux_amd64

  - name: publish
    image: plugins/docker:17.12
    settings:
      repo: lotteryjs/ten-minutes-app-api
      auto_tag: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
        
  - name: scp
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      target: /data/wwwroot/tenapi
      source: docker-compose.yml

  - name: ssh
    image: appleboy/drone-ssh
    pull: true
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      script:
        - docker-compose pull backend
        - docker-compose up -d --force-recreate --no-deps backend
        - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
  
trigger:
  event:
    - tag
