# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  port: 6868 # the port the HTTP server will listen on
  
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

database: # for database see (configure database section)
  dbname: typicode
  connection: mongodb://root:123456@localhost:27017

defaultuser: # on database creation, api creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)

